---
- name: Configure Github backup service
  hosts: lib-backups
  gather_facts: true
  become: true

  vars:
    - do_update: false
  vars_files:
    - vars/rbenv.yml
    - vars/backup.yml

  roles:
    - role: geerlingguy.repo-epel
    - role: zzet.rbenv

  pre_tasks:
    - name: Update System Packages
      package:
        name: '*'
        state: latest
      when: do_update

  post_tasks:
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ backups_dependencies }}"

    - name: Install Github Backup gem
      become: false
      become_user: "{{ backups_user }}"
      git:
        repo: "{{ backups_repo_url }}"
        dest: "{{ backups_repo_dest }}"

    - name: Bundle install gem dependencies
      become: false
      become_user: "{{ backups_user }}"
      bundler:
        state: present
        gemfile: "{{ backups_repo_dest }}/Gemfile"

    - name: Install pexpect via pip
      pip:
        name: pexpect
        version: 4.2

- import_playbook: backup.yml
