---
- name: Configure Github backup service
  hosts: lib-backups

  vars:
    - do_update: false
  vars_files:
    - vars/rbenv.yml
    - vars/backup.yml

  roles:
    - { role: geerlingguy.repo-epel, become: true }
    - { role: zzet.rbenv, become: true }

  pre_tasks:
    - name: Update System Packages
      become: true
      package:
        name: '*'
        state: latest
      when: do_update

  post_tasks:
    - name: Install dependencies
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ backups_dependencies }}"

    - name: Clone Github Backup repository
      git:
        repo: "{{ backups_repo_url }}"
        dest: "{{ backups_repo_dest }}"
        version: "{{ backups_repo_version }}"

    - name: Bundle install gem dependencies
      bundler:
        state: present
        gemfile: "{{ backups_repo_dest }}/Gemfile"

    - name: Install pexpect via pip
      become: true
      pip:
        name: pexpect
        version: 4.2

- import_playbook: backup.yml
